### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by ebachelet** [MichaelDAlbrow/pyDIA#4]
Hi Michael

I tried again to run your example now I have a pyraf env running. It looks they night be a problem on recent CODE update : 
c_functions.so: cannot open shared object file: No such file or directory

I see c_functions.c but not .so, so maybe you did forget to compile before the push?

Best

**Comment by MichaelDAlbrow** [comment]
Hi Etienne

Did you type "make" after installing?

  Michael

**Comment by ebachelet** [comment]
Hi Michael

My bad... I go into this again and close this issue.
Thanks!
